#!/bin/sh
set -e

echo "Starting vibedom VM..."

# Initialize git repository from workspace (skip if already initialized)
if [ -d /work/repo/.git ]; then
    echo "Existing repo found at /work/repo, skipping clone"
    cd /work/repo
elif [ -d /mnt/workspace/.git ]; then
    echo "Cloning git repository from workspace..."
    git clone /mnt/workspace/.git /work/repo
    cd /work/repo

    # Checkout the same branch user is on
    CURRENT_BRANCH=$(git -C /mnt/workspace rev-parse --abbrev-ref HEAD 2>/dev/null || echo "main")
    echo "Detected branch: $CURRENT_BRANCH"

    # Checkout branch (create if doesn't exist locally)
    if git show-ref --verify --quiet refs/heads/"$CURRENT_BRANCH"; then
        git checkout "$CURRENT_BRANCH"
    else
        git checkout -b "$CURRENT_BRANCH"
    fi

    echo "Working on branch: $CURRENT_BRANCH"

    # Copy .env* files from workspace (typically gitignored but needed at runtime)
    for env_file in /mnt/workspace/.env /mnt/workspace/.env.*; do
        [ -f "$env_file" ] && cp "$env_file" /work/repo/ && echo "Copied $(basename $env_file)"
    done
else
    echo "Non-git workspace, initializing fresh repository..."
    mkdir -p /work/repo
    rsync -a --exclude='.git' /mnt/workspace/ /work/repo/ || true
    cd /work/repo
    git init

    # Set git identity for agent commits
    git config user.name "Vibedom Agent"
    git config user.email "agent@vibedom.local"

    git add .
    git commit -m "Initial snapshot from vibedom session" || echo "No files to commit"
fi

# Set git identity for agent commits (for git workspaces)
git config user.name "Vibedom Agent"
git config user.email "agent@vibedom.local"

echo "Git repository initialized at /work/repo"

# Restore Claude config from persistent volume
# Claude Code writes to /root/.claude.json via atomic rename, which breaks symlinks.
# Instead of fighting that, we copy the file in on startup and periodically sync it back.
CLAUDE_CONFIG=/root/.claude.json
CLAUDE_CONFIG_PERSIST=/root/.claude/.claude.json.persist
if [ -f "$CLAUDE_CONFIG_PERSIST" ]; then
    cp "$CLAUDE_CONFIG_PERSIST" "$CLAUDE_CONFIG"
    echo "Restored Claude config from persistent storage"
else
    echo "No previous Claude config found (first run)"
fi

# Start SSH agent with deploy key at a fixed socket path so exec sessions can use it
# Skip if socket already exists (container restart)
if [ -f /mnt/config/keys/id_ed25519_vibedom ] && [ ! -S /tmp/ssh-agent.sock ]; then
    ssh-agent -a /tmp/ssh-agent.sock > /dev/null
    SSH_AUTH_SOCK=/tmp/ssh-agent.sock ssh-add /mnt/config/keys/id_ed25519_vibedom 2>/dev/null || true
    echo "SSH_AUTH_SOCK=/tmp/ssh-agent.sock" >> /etc/environment
    export SSH_AUTH_SOCK=/tmp/ssh-agent.sock
elif [ -S /tmp/ssh-agent.sock ]; then
    echo "SSH agent already running"
    export SSH_AUTH_SOCK=/tmp/ssh-agent.sock
fi

# Proxy environment variables are set by container runtime (-e flags)
# and are available to all processes including docker exec sessions
echo "Configuring explicit proxy mode..."
echo "Proxy: HTTP_PROXY=$HTTP_PROXY"

# Install vibedom proxy CA certificate (generated by host-side mitmproxy)
echo "Installing vibedom CA certificate..."
CA_CERT=/mnt/config/mitmproxy/mitmproxy-ca-cert.pem
if [ -f "$CA_CERT" ]; then
    mkdir -p /usr/local/share/ca-certificates
    cp "$CA_CERT" /usr/local/share/ca-certificates/vibedom-ca.crt
    update-ca-certificates 2>/dev/null || true
    export REQUESTS_CA_BUNDLE=/etc/ssl/certs/ca-certificates.crt
    export SSL_CERT_FILE=/etc/ssl/certs/ca-certificates.crt
    export CURL_CA_BUNDLE=/etc/ssl/certs/ca-certificates.crt
    export NODE_EXTRA_CA_CERTS=/etc/ssl/certs/ca-certificates.crt
    echo "CA certificate installed"
else
    echo "Warning: CA cert not found at $CA_CERT"
fi

# Inject host aliases from VIBEDOM_HOST_ALIASES env var (used by apple/container runtime)
# Format: hostname1=ip1,hostname2=ip2
if [ -n "$VIBEDOM_HOST_ALIASES" ]; then
    echo "Adding host aliases to /etc/hosts..."
    echo "$VIBEDOM_HOST_ALIASES" | tr ',' '\n' | while IFS='=' read -r hostname ip; do
        echo "$ip $hostname" >> /etc/hosts
        echo "Added host alias: $hostname -> $ip"
    done
fi

# Signal readiness
touch /tmp/.vm-ready

echo "VM ready!"

# Keep container running and periodically persist Claude config
sync_claude_config() {
    if [ -f "$CLAUDE_CONFIG" ]; then
        cp "$CLAUDE_CONFIG" "$CLAUDE_CONFIG_PERSIST" 2>/dev/null || true
    fi
}
trap 'sync_claude_config; exit 0' SIGTERM SIGINT

while true; do
    sync_claude_config
    sleep 30
done
